name: Run IXL Stats Scraper

on:
  schedule:
    - cron: '0 22 * * *'  # Runs at 00:00 UTC every day
  pull_request:
    branches: [main]  # Triggers on PRs to main branch  
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run IXL Stats Scraper
      env:
        IXL_USERNAME: ${{ secrets.IXL_USERNAME }}
        IXL_PASSWORD: ${{ secrets.IXL_PASSWORD }}
      run: python get_stats.py

    - name: Upload screenshot on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: error-screenshot
        path: error_screenshot.png