name: Run IXL Stats Scraper

on:
  schedule:
    - cron: '59 23 * * *'  # Runs at 23:59 UTC every day
  pull_request:
    branches: [main]  # Triggers on PRs to main branch  
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Check credentials
      run: python check_credentials.py
      env:
        IXL_USERNAME: ${{ secrets.IXL_USERNAME }}
        IXL_PASSWORD: ${{ secrets.IXL_PASSWORD }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        MATHACADEMY_USERNAME: ${{ secrets.MATHACADEMY_USERNAME }}
        MATHACADEMY_PASSWORD: ${{ secrets.MATHACADEMY_PASSWORD }}
        MATHACADEMY_STUDENT_IDS: ${{ secrets.MATHACADEMY_STUDENT_IDS }}

    - name: Run IXL Stats Scraper
      env:
        IXL_USERNAME: ${{ secrets.IXL_USERNAME }}
        IXL_PASSWORD: ${{ secrets.IXL_PASSWORD }}
        HEADLESS: 'true'
        SEND_EMAIL: ${{ github.event_name == 'schedule' }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        MATHACADEMY_USERNAME: ${{ secrets.MATHACADEMY_USERNAME }}
        MATHACADEMY_PASSWORD: ${{ secrets.MATHACADEMY_PASSWORD }}
        MATHACADEMY_STUDENT_IDS: ${{ secrets.MATHACADEMY_STUDENT_IDS }}
      run: python get_stats.py
      
    - name: Upload screenshot on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error-screenshot
        path: error_screenshot.png
